import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PawPal</title>
        <meta name="description" content="PawPal generated by create next app" />
        <link rel="icon" href="/bone.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>Welcome to PawPal!</p>
          <a href="/api/auth/signin">Enter!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a>
          <span className={styles.logo}>
            <Image src="/PawPalLogo.jpg" alt="PawPal Logo" width={80} height={60} />
          </span>
        </a>
      </footer>
    </div>
  )
}
